final.out: ./includes/utility_foos.cpp ./includes/pi_calculations.cpp main.cpp
	g++ -std=c++11 ./includes/utility_foos.cpp ./includes/pi_calculations.cpp main.cpp -o final.out

clean:
	rm *.o final.out